import type {Metadata} from "next";
import {ToastContainer} from "react-toastify";
import Navbar from "@/comporents/Navbar";
import Footer from "@/comporents/Footer";

export const metadata: Metadata = {
    title: "Chat-app/settings",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body >
                <ToastContainer position="top-center" autoClose={3000} style={{ zIndex: 9999 }}/>
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}